#!/bin/sh

adapterpath="../bridge" #path to adapter (non-bare, non-working) Git repo
initcount=1 #number of initial (administrative) SVN commits per branch

unset GIT_DIR
cd $adapterpath

git fetch
remotebranches=`git branch -r | grep origin/ | cut -d / -f 2`
for eachbranch in $remotebranches
	do
		if git branch | grep $eachbranch #this was an existing branch
			then
				git checkout $eachbranch
			else #this is a new branch
				svn mkdir -m "Create branch $eachbranch" `git config --local svn-remote.svn.url`/branches/$eachbranch
				git svn fetch
				git checkout -b $eachbranch $eachbranch
			fi
		
		localcount=`git log --oneline --first-parent | wc -l`
		remotecount=`git log --oneline origin/$eachbranch --first-parent | wc -l`
		neededcount=$(($remotecount-$localcount+$initcount))
		neededhashes=`git log --oneline --reverse --first-parent -$neededcount origin/$eachbranch | cut -d \  -f 1`
		for commithash in $neededhashes
			do
				git cherry-pick $commithash || git cherry-pick -m 1 $commithash
			done
		
		git svn dcommit
	done

git checkout master
