#!/bin/sh

# Copyright (C) 2012-13 Sol Boucher
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with it.  If not, see <http://www.gnu.org/licenses/>.

. hooks/vars.sh
lockpath=$adapterpath/.git/$lockfile

if [ -e $lockpath ] #we're locked out
	then
		echo
		echo "ERROR: The SVN repository is currently locked"
		echo "  This could either mean that someone else is pushing changes at"
		echo "  this very moment, or that a recent push operation terminated"
		echo "  abnormally.  Please try again after a minute or two."
		echo "  If the problem persists, contact our configuration manager."
		false #only allow one push and one svn dcommit at a time
	else #no concurrent modification attempt
		echo -n 0 > $lockpath #nothing has failed yet
		refcount=0; while read line; do refcount=$(($refcount+1)); done #count incoming refs
		echo -n $refcount > $lockpath$totalextension #how many refs are we pushing?
		true
	fi
